name: Build and release binary
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.3'
    - name: Build
      run: go build -buildmode=pie -trimpath -o build/metadater
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: xz
        GHR_PATH: build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
